# Generated by Django 2.2.3 on 2019-07-21 19:37

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Year cannot be a negative value.')])),
                ('rated', models.CharField(max_length=64, null=True)),
                ('released', models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2019, 7, 21), 'Release date cannot be greater that current date.')])),
                ('runtime', models.CharField(max_length=64)),
                ('genre', models.CharField(max_length=256)),
                ('director', models.CharField(max_length=255, null=True)),
                ('writer', models.CharField(max_length=512, null=True)),
                ('actors', models.CharField(max_length=512, null=True)),
                ('plot', models.TextField(null=True)),
                ('language', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=128)),
                ('awards', models.CharField(max_length=512, null=True)),
                ('poster', models.URLField(null=True)),
                ('metascore', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Metascore cannot be a negative value.'), django.core.validators.MaxValueValidator(100, 'Metascore cannot be greater than 100.')])),
                ('imdbrating', models.FloatField(validators=[django.core.validators.MinValueValidator(0, 'Rating cannot be a negative value.'), django.core.validators.MaxValueValidator(10, 'Rating cannot be greater than 10.')])),
                ('imdbvotes', models.CharField(max_length=24)),
                ('imdbid', models.CharField(max_length=9)),
                ('type', models.CharField(max_length=32)),
                ('dvd', models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2019, 7, 21), 'DVD date cannot be greater than current date.')])),
                ('boxoffice', models.CharField(max_length=24, null=True)),
                ('production', models.CharField(max_length=255, null=True)),
                ('website', models.URLField(null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='movies.Movie')),
            ],
        ),
    ]
